### PR TITLE
Add table prefix configurations

### PR DESCRIPTION
**Pull request by sanathks**
By merging this PR you will be able to configure chatter table prefixes because some people (like me :)) eager to have their own table prefix or they don't like to have table prefix. 

Features:
- Can enable or disable table prefix
- Can have custom table prefix

### CODE REVIEW

**Comment by sanathks** [comment]
@tnylea Any comments on this?

**Comment by marktopper** [comment]
Hey.
Sorry for the late reply.

Wouldn't it be easier if the underscore (`_`) was a part of the actual prefix in the configuration?

**Comment by sanathks** [comment]
Yeah, that would be easier. I'll update the PR.

**Comment by marktopper** [comment]
Wonderful 👍

**Comment by marktopper** [comment]
Closed due to inactivity.

**Pull request closed without merging**
