### PR TITLE
Update ChatterBeforeNewDiscussion.php

### PR DESCRIPTION
**Pull request by marktopper**
http://stackoverflow.com/questions/43078096/validator-error-when-posting-a-thread-in-laravel-chatter/43078893

### CODE REVIEW

**Comment by Chinese1904** [comment]
I assume it has to be changed in ChatterBeforeNewResponse.php as well?

**Comment by nithishm** [comment]
Yeah, it needs to fixed in ChatterBeforeNewResponse.php as well.

Both ChatterBeforeNewResponse.php & ChatterBeforeNewDiscussion.php
have `use Validator;` in 0.2.7

**Comment by Chinese1904** [comment]
There has been a merged pull request for a few weeks that fixes it already 👍🏽

**Comment by marktopper** [comment]
What pull request @Chinese1904 😄

**Comment by Chinese1904** [comment]
@marktopper 
https://github.com/thedevdojo/chatter/pull/80 This one should be it. 👍

**Comment by marktopper** [comment]
Thanks, closing this.

**Pull request closed without merging**
