### PR TITLE
Fix Discussion-Category relationship

### PR DESCRIPTION
**Pull request by ryanvade**
The category ID in chatter_discussion needs to be chatter_category_id not category_id.

### CODE REVIEW

**Comment by ryanvade** [comment]
Travis CI environment error..

**Comment by ryanvade** [comment]
Updates?

**Comment by marktopper** [comment]
Thanks, just tested this manually. Since we (for some reasons) don't have Travis anymore?

**Comment by firescript** [comment]
when I use the category model directly to query a discussion
`{{dd($category->discussions)}}`
 i get the error 
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'chatter_discussion.category_id' in 'where clause' (SQL: select * from `chatter_discussion` where `chatter_discussion`.`category_id` = 1 and `chatter_discussion`.`category_id` is not null and `chatter_discussion`.`deleted_at` is null) (View: /home/vagrant/Code/machealth/resources/views/admin/discussions/discussion-index.blade.php)
```
This is because eloquent is looking for the default naming convention category_id but you guys named it chatter_category_id .. is there something that needs to change in the discussion model? or am i doing something wrong here?

**Pull request merged**
