### PR TITLE
Add localization files

### PR DESCRIPTION
**Pull request by insoutt**
Implement localizations for non english people.

### CODE REVIEW

**Comment by johnnymast** [comment]
Shout me out if there is going to be a need for dutch translations i will help.

**Comment by insoutt** [comment]
@johnnymast Yes you can add dutch translation will be helpful, for the moment I am adding spanish translations.

**Comment by johnnymast** [comment]
@insoutt nice! i will do it later this week.

**Comment by marktopper** [comment]
Merging into `release/0.3`, this will hopefully soon be released.

**Pull request merged**
