### PR TITLE
languages improved + fix repeated js in discussions

### PR DESCRIPTION
**Pull request by galdazbiz**
I hope you better like this way to integrate the titles.
Additionally chatter.js was duplicated in discussions when you select the sidebar in the config, now solved.
I have also new views, mobile friendly, I changed it 30%, not sure if to create a pull request, add them as new "vendor" template..

### CODE REVIEW

**Comment by galdazbiz** [comment]
I also added a "if" in discussion and home to be able to configure the alerts externally in case there's a system in the template already managing all the alerts from the site.

**Comment by galdazbiz** [comment]
not merged yet??

**Comment by marktopper** [comment]
Thanks

**Comment by gerbenjacobs** [comment]
I have two questions.

- Shouldn't the `errors` attribute config be set to "true" by default?
- Why are we using this `strtolower(trans('chatter::intro.titles.discussion'))` in the translation files? If you now set it to "Discussions" in the config, all languages will use that word.

**Comment by marktopper** [comment]
> Shouldn't the errors attribute config be set to "true" by default?
Nice catch, fixed in #177

> Why are we using this strtolower(trans('chatter::intro.titles.discussion')) in the translation files? If you now set it to "Discussions" in the config, all languages will use that word.
You might want to translate `Discussions` to the other languages as well.

**Comment by gerbenjacobs** [comment]
But in that case you need:

> chatter::intro.titles.discussion.en = Discussion
> chatter::intro.titles.discussion.es = Discusión
> chatter::intro.titles.discussion.nl = Discussie

Also I just found out there's a problem with UTF-8 and `strtolower`. This needs to become [mb_strtolower](http://php.net/manual/en/function.mb-strtolower.php) to keep multi-byte/encoding issues at bay.

Although my preference is to not use Config settings in translations at all.

**Comment by galdazbiz** [comment]
@gerbenjacobs 

You're right with the "true" errors

Regarding using 'chatter::intro.titles.discussion' this word is taken from a file in lang, not in config,  it was like that before, but I changed it in this fix, because I agree better not to use config for words.

And yes, mb_strtolower might be better, I use that because in some languages you can capitalise al the words in a sentence, but in others is not correct.

**Pull request merged**
